apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-screener-config
  labels:
    app: resume-screener
data:
  # Base URL of the API for any dynamic integrations
  BACKEND_API_URL: "http://resume-screener-backend-service:8000"
